dtreeplacement_web/items/forms.py
import wtforms
from wtforms.validators import DataRequired
from models import Item
from helpers import get_items


class ItemForm(wtforms.Form):
    # e.g., "Superman #75"
    content = wtforms.StringField(
        'Content',
        validators=[DataRequired()],
        description='e.g., "Superman #75"'
    )
    # items to select as "parents" for this item
    groups = wtforms.SelectMultipleField(
        'Groups',
        # eventually this will be a search box w/ autocomplete
        # choices will get filled in __init__()
        coerce=int,
        description='Select the groups this item should be a member of.'
    )

    def __init__(self, *args, **kwargs):
        wtforms.Form.__init__(self, *args, **kwargs)

        # if we're editing, fill in the existing data
        if 'item' in kwargs:
            item = kwargs['item']
            self.content.data = item.content

            # populate the groups list
            # if we're editing, don't include this item in the list of groups
            all_groups = Item.query\
                .filter(Item.id != item.id, Item.status == Item.STATUS_NORMAL)\
                .order_by(Item.content.asc()).all()

            # the groups that should already be selected on load
            self.groups.data = [group.id for group in item.groups]
        else:
            # only if we're NOT editing an existing item
            # populate the groups list
            all_groups = get_items()

        # populate the groups list
        self.groups.choices = \
            [(group.id, group.content) for group in all_groups]

dtreeplacement_web/items/blueprint.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from models import Item
from items.forms import ItemForm
from app import db
from helpers import get_items, get_deleted_items

items = Blueprint('items', __name__, template_folder='templates')


@items.route('/')
def index():
    return render_template('items/index.j2', items=get_items(),
                           deleted_items=get_deleted_items())


@items.route('/<int:item_id>')
def detail(item_id):
    # retrieve item
    item = Item.query.filter(Item.id == item_id).first_or_404()

    # todo: filter out deleted items
    return render_template(
        'items/detail.j2',
        item=item,
        groups=item.groups,
        members=item.members
    )


@items.route('/add', methods=['GET', 'POST'])
def add():
    # if we're getting POST data, add the new entry
    if request.method == 'POST':
        form = ItemForm(request.form)
        if form.validate():
            # create an Item and fill it with the form data
            # (remember, the groups aren't accounted for right here)
            item = Item(form.content.data)

            # then add the appropriate memberships
            for group_id in form.groups.data:
                item.members.append(Item.query.get(group_id))

            # commit the changes
            db.session.add(item)
            db.session.commit()

            # then redirect to the item detail for the added item
            flash('Item {} has been added.'.format(item.id), 'info')
            return redirect(url_for('items.detail', item_id=item.id))
        else:
            # todo: something better
            print("form didn't validate")
            print(form.errors)

    # otherwise show the add item form
    else:
        form = ItemForm()

    return render_template('items/add.j2', form=form)


@items.route('/<item_id>/edit', methods=['GET', 'POST'])
def edit(item_id):
    # retrieve the item we're going to edit
    item = Item.query.filter(Item.id == item_id).first_or_404()

    if request.method == 'POST':
        # we received data, so modify the database
        form = ItemForm(request.form, obj=item)
        if form.validate():
            # replace the content
            item.content = form.content.data

            # replace the list of groups
            item.groups =\
                [Item.query.get(group_id) for group_id in form.groups.data]

            # commit our changes
            db.session.add(item)
            db.session.commit()

            # then redirect to the detail for the changed item
            flash('Item {} successfully edited.'.format(item.id), 'info')
            return redirect(url_for('items.detail', item_id=item.id))
        else:
            # todo: something better
            print("form didn't validate")
            print(form.errors)
    else:
        # we didn't receive data, so display the form
        form = ItemForm(item=item)

    return render_template('items/edit.j2', item=item, form=form)


@items.route('/<item_id>/delete', methods=['GET', 'POST'])
def delete(item_id):
    item = Item.query.filter(Item.id == item_id).first_or_404()
    if request.method == 'POST':
        item.status = Item.STATUS_DELETED
        db.session.add(item)
        db.session.commit()
        flash('Item {} successfully deleted.'.format(item.id), 'info')
        return redirect(url_for('items.index'))

    return render_template('items/delete.j2', item=item)


@items.route('/<item_id>/restore', methods=['POST'])
def restore(item_id):
    item = Item.query.filter(Item.id == item_id).first_or_404()
    if item.status == Item.STATUS_DELETED:
        item.status = Item.STATUS_NORMAL
        db.session.add(item)
        db.session.commit()

    # todo: some sort of error reporting is needed here
    flash('Item {} successfully restored.'.format(item.id), 'info')
    return redirect(url_for('items.detail', item_id=item_id))


@items.errorhandler(404)
def item_not_found(error):
    return render_template('items/detail.j2', item=None), 404

dtreeplacement_web/items/templates/items/add.j2
{% extends "base.j2" %}
{% block title %}Add item{% endblock %}
{% block content %}
    <form action="{{ url_for('items.add') }}" method="post">
        {% for field in form %}
            {{ field.label() }}
            {{ field() }}
            {%- for error in field.errors %}<span class="error">{{ error }}</span>{%- endfor %}
        {% endfor %}
        <button type="submit">Add item</button>
        <a href="{{ url_for('items.index') }}">Cancel</a>
    </form>
{% endblock content %}

dtreeplacement_web/items/templates/items/delete.j2
{% extends "base.j2" %}
{% block title %}Delete {{ item.content }}{% endblock %}
{% block content %}
    <h2>Delete item {{ item.id }}: "{{ item.content }}"</h2>
    <form action="{{ url_for('items.delete', item_id=item.id) }}" method="post">
        <button type="submit">Delete</button>
        <a href="{{ url_for('items.detail', item_id=item.id) }}">Cancel</a>
    </form>
{% endblock content %}

dtreeplacement_web/items/templates/items/detail.j2
{% extends 'base.j2' %}
{% from "macros/item_link.j2" import item_link %}
{% block title %}Item Detail{% endblock %}
{% block content %}
    {%- if item %}
    <h2>Item detail</h2>
    <ul>
        <li>ID: <code>{{ item.id }}</code></li>
        <li>Content: <code>{{ item.content }}</code></li>
        <li>Created: <code>{{ item.created_timestamp }}</code></li>
        <li>Modified: <code>{{ item.modified_timestamp }}</code></li>
        <li>Status: <code>{{ item.status }}</code></li>
        {%- if groups %}
            <li>Member of:
            {% for group in groups %}
                {{ item_link(group) -}}
                {% if loop.last != True %},  {% endif %}
            {% endfor %}
            </li>
        {% endif %}
        {% if members %}
            <li>Members:
            {% for member in members %}
                {{ item_link(member) -}}
                {% if loop.last != True %},  {% endif %}
            {% endfor %}
            </li>
        {%- endif %}
    </ul>
    {% else %}
        <p>No item found with that ID.</p>
    {% endif %}
    <ul>
        {%- if item %}
            <a href="{{ url_for('items.edit', item_id=item.id) }}">Edit item</a>
            <!--fixme: I want this to test against Item.STATUS_DELETED instead of a hardcoded int-->
            {%- if item.status == 1 %}
                <form action="{{ url_for('items.restore', item_id=item.id) }}" method="post">
                    <button type="submit">Restore item</button>
                </form>
            {%- else %}
                <a href="{{ url_for('items.delete', item_id=item.id) }}">Delete item</a>
            {%- endif %}
        {%- endif %}
        <a href="{{ url_for('items.index') }}">Back to item index</a>
    </ul>
{% endblock content %}

dtreeplacement_web/items/templates/items/edit.j2
{% extends "base.j2" %}
{% from "macros/form_field.j2" import form_field %}
{% block title %}Edit item{% endblock %}
{% block content %}
    <form action="{{ url_for('items.edit', item_id=item.id) }}" method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        <div>
            <button type="submit">Save changes</button>
            <a href="{{ url_for('items.detail', item_id=item.id) }}">Cancel</a>
        </div>
    </form>
{% endblock content %}

dtreeplacement_web/items/templates/items/index.j2
{% extends 'base.j2' %}
{% block title %}Items{% endblock %}
{% block content %}
    <h2>Items</h2>
    <ul>
    {% for item in items %}
        <li><a href="{{ url_for('items.detail', item_id=item.id) }}">{{ item.content }}</a></li>
    {% endfor %}
    </ul>

    {% if deleted_items %}
        <h2>Deleted items</h2>
        <ul>
        {% for item in deleted_items %}
            <li><a href="{{ url_for('items.detail', item_id=item.id) }}">{{ item.content }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}

    <hr />
    <ul>
        <li><a href="{{ url_for('items.add') }}">Add item</a></li>
        <li><a href="{{ url_for('index') }}">Back to index</a></li>
    </ul>
{% endblock content %}

dtreeplacement_web/items/templates/items/item_detail.j2
{% extends 'base.j2' %}
{% block title %}Item Detail{% endblock %}
{% block content %}
    {%- if item %}
    <h2>Item detail</h2>
    <ul>
        <li>ID: <code>{{ item.id }}</code></li>
        <li>Content: <code>{{ item.content }}</code></li>
        <li>Created: <code>{{ item.created_timestamp }}</code></li>
        <li>Modified: <code>{{ item.modified_timestamp }}</code></li>
        {%- if groups %}
            <li>Member of:
            {% macro item_link(item_id, item_content) -%}
                <a href="{{ url_for('items.item_detail', item_id=item_id) }}">{{ item_content }}</a>
            {%- endmacro -%}
            {%- for group in groups -%}
                <!--{{ "<a href='%s'>%s</a>"|format(url_for('items.item_detail', item_id=group.id), group.content) }}-->
                {{- item_link(group.id, group.content) -}}
                {%- if loop.last != True -%},  {% endif -%}
            {%- endfor -%}
            </li>
        {%- endif %}
    </ul>
    {% else %}
        <p>No item found with that ID.</p>
    {% endif %}
    <ul>
        <a href="{{ url_for('items.edit', item_id=item.id) }}">Edit item</a>
        <a href="{{ url_for('items.index') }}">Back to item index</a>
    </ul>
{% endblock content %}